chore: update discovery doc generation to discovery-artifact-manage
googleapis/google-api-nodejs-client pull request #3520
Opened 2024-07-17 23:14 UTC by sofisl

2024-07-17 23:54 UTC, chingor13 requested changes
I would separate the change to the download tool from the client update.

2024-07-17 23:54 UTC, chingor13 commented on src/generator/download.ts
> +      const url = `${options.discoveryUrl}/${api.id.replace(':', '.')}.json`;
I would use api.name + api.version as that is what the discovery cache updater uses to build the filename. I can't guarantee that api.id is the same.

2024-07-18 15:03 UTC, chingor13 requested changes
The change to the actual discovery document url (`<service>.<version>.json`) appears to have been reverted

2024-07-18 15:57 UTC, chingor13 approved these changes

2024-07-18 16:41 UTC, danielbankhead approved these changes

2024-07-18 16:42 UTC, merged